name-template: 'Release v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'New Features'
    labels:
      - 'major feature'
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug fix'
  - title: 'Maintenance'
    labels: 
      - 'dependencies'
      - 'documentation'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major feature'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug fix'
      - 'documentation'
  default: patch
  
template: |
  ## Changes

  $CHANGES
