name: Bug report
description: Create a report for a bug you have found
title: "[BUG] <title>"
labels: "bug"
assignees: Pavocracy
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues and did not find this bug reported
      required: true
- type: textarea
  attributes:
    label: Describe the bug
    placeholder: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    placeholder: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    placeholder: |
      1. Do this
      2: Do that
      3. See error or incorrect behavior
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment details
    value: |
      - OS:
      - python:
      - leetscraper:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    placeholder: |
      Please attach your leetscraper.log file to this bug report. You can find the log file where leetscraper was imported from. In most cases this will be site-packages/leetscraper directory. Feel free to add any other links or references that are relevant for this bug report.  
  validations:
    required: false
