name: Feature request
description: Suggest an idea for this project
title: "[REQUEST] <title>"
labels: "enhancement"
assignees: Pavocracy
body:
- type: checkboxes
  attributes:
    label: Is there an existing request for this?
    description: Please search to see if an issue already exists for this requested feature.
    options:
    - label: I have searched the existing issues and did not find this feature requested
      required: true
- type: textarea
  attributes:
    label: Feature you would like to see in leetscraper
    placeholder: A clear and concise description of what the functionality is that you want, or an additional website you would like supported.
  validations:
    required: true
- type: textarea
  attributes:
    label: Is this requested feature relevant for this project?
    placeholder: Quick explanation of why you think this makes sense to be added to this project. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Do you have any experience or working code examples to help implement this feature?
    placeholder: If you have already tried to do this yourself, or know technical details of whats required and willing to share, please do so!
  validations:
    required: false
