name: 'Auto Label'

on:
  pull_request:
    types: [ opened ]
    branches: [ main ]

jobs:
  apply-PR-label:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Check event context'
      run: echo '${{ toJSON(github.event) }}'

    - name: 'Bug Fix Label'
      uses: actions/github-script@v6
      if: ${{ contains(github.event.body, '[x] Bug Fix') }}
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['bug fix']
          })

    - name: 'Documentation Label'
      uses: actions/github-script@v6
      if: ${{ contains(github.event.body, '[x] Documentation') }}
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['documentation']
          })

    - name: 'Feature Label'
      uses: actions/github-script@v6
      if: ${{ 
        contains(github.event.body, '[x] New Feature') ||
        contains(github.event.body, '[x] Code Addition') }}
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['feature']
          })

    - name: 'Major Feature Label'
      uses: actions/github-script@v6
      if: ${{ contains(github.event.body, '[x] Major Feature') }}
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['major feature']
          })
