name: 'Auto Comment'

on:
  pull_request:
    types: [ opened ]
    branches: [ main ]
  issues:
    types: [ opened ]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    
    - name: 'Comment on PR'
      uses: actions/github-script@v6
      if: ${{ github.event.pull_request }}
      with:
        github-token: ${{ secrets.WORKFLOW_PAT }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Thank you for your contribution! Please make sure you have read our docs on [contributing](https://github.com/Pavocracy/leetscraper/blob/main/docs/CONTRIBUTING.md)'
          })

    - name: 'Comment on Issues'
      uses: actions/github-script@v6
      if: ${{ github.event.issue }}
      with:
        github-token: ${{ secrets.WORKFLOW_PAT }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Thank you for your contribution! Please make sure you have read our docs on [submitting issues](https://github.com/Pavocracy/leetscraper/blob/main/docs/SUBMITTING_ISSUES.md)'
          })
