name: 'Build on Release'

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout PR' 
      uses: actions/checkout@v3
      with:
        ref: main

    - name: 'Setup Python'
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: 'Update version'
      run:
        sed -i 's/[0-9].[0-9].[0-9]/'$VERSION'/' src/leetscraper/__init__.py
      env:  
        VERSION: ${{ github.event.release.tag_name }}

    - name: 'Build New Release'
      run: |
        rm -rf dist/
        python -m pip install --upgrade pip
        pip install build
        python -m build

    - name: 'Import GPG key'
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: 'Sign build files'
    # Signed using RSA key 9A5D2D5AA10873B9ABCD92F1D959AEE8875DEEE6
      run: |
        gpg --list-keys
        bash gpg-sign.sh

    - name: 'Commit Build Files'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build new release

    - name: 'Upload dist files to release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
