name: 'Build on Release'

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout PR' 
      uses: actions/checkout@v3
      with:
        ref: main

    - name: 'Setup Python'
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: 'Update version'
      run:
        sed -i 's/[0-9].[0-9].[0-9]/'$VERSION'/' src/leetscraper/__init__.py
      env:  
        VERSION: ${{ github.event.release.tag_name }}

    - name: 'Build New Release'
      run: |
        rm -rf dist/
        python -m pip install --upgrade pip
        pip install build
        python -m build

    - name: 'Commit Build Files'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build new release
