name: 'Code Coverage'

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  code_cov:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout PR' 
      uses: actions/checkout@v3

    - name: 'Setup Python'
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: 'Install Requirements'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 'Get Unittest Coverage Report'
      run: |
        python -m coverage run -m unittest discover
        python -m coverage xml

    - name: 'Upload Coverage Report'
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
