name: 'Code Coverage'

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  code_cov:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Get Unittest Coverage Report'
      run: |
        python -m coverage run -m unittest discover
        python -m coverage xml

    - name: 'Upload Coverage Report'
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
