name: 'Code Coverage'

on:
  push:
    branches: [ main ]

jobs:
  code_cov:
    runs-on: ubuntu-latest
    # Only run if this push is from a pull request merge
    if: ${{ contains(github.event.head_commit.message, 'Merge pull request') }}
    steps:
    
    - name: 'Checkout PR' 
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.WORKFLOW_PAT }}

    - name: 'Setup Python'
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: 'Install Requirements'
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 'Get Unittest Coverage Report'
      env:
        # This is needed to authenticate with githubs API to avoid rate limits
        # See further details about gh_token from the webdriver_manager repo
        # https://github.com/SergeyPirogov/webdriver_manager#gh_token
        GH_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      run: |
        python3 -m coverage run -m unittest discover
        python3 -m coverage report
        python3 -m coverage xml

    - name: 'Upload Coverage Report'
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
