name: 'Code Coverage'

on:
  push:
    branches: [ main ]

jobs:
  code_cov:
    # Only run if this push is from a pull request merge
    if: ${{ contains(github.event.head_commit.message, 'Merge pull request') }}
    runs-on: ubuntu-latest
    env:
      # This is needed to authenticate with githubs API to avoid rate limits
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:      
    - name: 'Checkout PR' 
      uses: actions/checkout@v3
      with:
        ref: main

    - name: 'Setup Python'
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: 'Install Requirements'
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 'Get Unittest Coverage Report'
      run: |
        python3 -m coverage run -m unittest discover
        python3 -m coverage report
        python3 -m coverage xml

    - name: 'Upload Coverage Report'
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
