name: 'Dependabot auto-merge'

on:
  pull_request:
    types: [ labeled ]
    branches: [ main ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
    # This matches the user login in the event context
    # This seems to be more reliable than github.actor
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - uses: actions/github-script@v6
        with:
          # @dependabot merge allows dependabot to self merge
          # only when all the PR checks have run and pass
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@dependabot merge'
            })
