name: 'Monthly Release'

on:
  schedule:
    - cron: '00 * * * *'
    - cron: '15 * * * *'
    - cron: '30 * * * *'
    - cron: '45 * * * *'

jobs:
  monthly-release:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(releases);

            for (var i = 0; i < releases.length; i++) {
            console.log(releases[i]);
            };
