name: 'Monthly Release'

on:
  schedule:
    - cron: '00 00 1 * *'

jobs:
  monthly-release:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            for (let release of releases.data) {
              if (release.draft) {
                console.log('Publishing ${release.name}');
                github.rest.repos.updateRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: release.id,
                  draft: false
                });
                break;
              };
            };
