name: Pull Requests

on: pull_request

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Checkout PR' 
      uses: actions/checkout@v2

    - name: 'Setup Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.12

    - name: 'Install Requirements'
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: 'Run Checks'
      run: |
        black ./src/ --check
        mypy ./src/
        pylint ./src/ --fail-under=9 

    - name: 'Run Unit Tests'
      run:
        python -m unittest discover
        