name: Pull Requests

on: pull_request

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Checkout PR' 
      uses: actions/checkout@v2

    - name: 'Setup Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2

    - name: 'Install Requirements'
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: 'Install chrome'
      run: |
        curl -o chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        apt-get install ./chrome.deb -y

    - name: 'Run Checks'
      run: |
        black ./src/ -t py310 --check
        mypy ./src/
        pylint ./src/ --fail-under=9 

    - name: 'Run Unit Tests'
      run:
        python -m unittest discover
        