name: Publish package to pypi

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:    

    - name: 'Checkout PR' 
      uses: actions/checkout@v2

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: pavocracy
        password: ${{ secrets.PYPI_API_TOKEN }}