name: Publish package to pypi

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout PR' 
      uses: actions/checkout@v2

    - name: 'Setup Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine

    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: pavocracy
        password: ${{ secrets.PYPI_API_TOKEN }}