name: Publish package to pypi
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish package
      if: github.event_name == startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: pavocracy
        password: ${{ secrets.PYPI_API_TOKEN }}